version: '3.8'
services:
  app:
    build: .
    volumes:
      - .:/vman_django
    ports:
      - 8000:8484
    image: app:vman_django
    container_name: vman_django_container
    command: python manage.py runserver 0.0.0.0:8000
