# Generated by Django 3.2 on 2022-08-02 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='authorization',
            name='va_record',
            field=models.BooleanField(default=False),
        ),
    ]
