# Generated by Django 4.0.5 on 2022-07-09 06:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Authorization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dashboard', models.BooleanField(default=False)),
                ('coded_va_data', models.BooleanField(default=False)),
                ('create_graph', models.BooleanField(default=False)),
                ('create_table', models.BooleanField(default=False)),
                ('create_map', models.BooleanField(default=False)),
                ('concordant_vas', models.BooleanField(default=False)),
                ('discordant_vas', models.BooleanField(default=False)),
                ('coding_work', models.BooleanField(default=False)),
                ('update_profile', models.BooleanField(default=False)),
                ('system_user', models.BooleanField(default=False)),
                ('system_role', models.BooleanField(default=False)),
                ('icd_10_category', models.BooleanField(default=False)),
                ('interviewer_data', models.BooleanField(default=False)),
                ('organization', models.BooleanField(default=False)),
                ('upload_csmf', models.BooleanField(default=False)),
                ('icd_10_list', models.BooleanField(default=False)),
                ('settings', models.BooleanField(default=False)),
                ('download_data', models.BooleanField(default=False)),
                ('user_authorization', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('authorise_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Authorization List',
            },
        ),
    ]
