# Generated by Django 4.0.5 on 2022-07-09 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_authorization'),
    ]

    operations = [
        migrations.RenameField(
            model_name='authorization',
            old_name='authorise_user',
            new_name='authorize_user',
        ),
    ]
