# Generated by Django 3.2 on 2022-08-15 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_authorization_va_record'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actees',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='fieldkeys',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='forms',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='publiclinks',
            options={'managed': True},
        ),
    ]
