# Generated by Django 4.0.5 on 2022-07-11 07:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_rename_authorise_user_authorization_authorize_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='CSMFData',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('upload_csmf_dataset', models.FileField(upload_to='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'CSMF Data',
            },
        ),
    ]
