# Generated by Django 3.2 on 2022-08-15 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20220815_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldkeys',
            name='createdby',
            field=models.ForeignKey(blank=True, db_column='createdBy', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_by', to='dashboard.actors'),
        ),
        migrations.AddField(
            model_name='fieldkeys',
            name='projectid',
            field=models.ForeignKey(blank=True, db_column='projectId', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dashboard.projects'),
        ),
        migrations.AddField(
            model_name='forms',
            name='currentdefid',
            field=models.ForeignKey(blank=True, db_column='currentDefId', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='currentdefid', to='dashboard.formdefs'),
        ),
        migrations.AddField(
            model_name='forms',
            name='draftdefid',
            field=models.ForeignKey(blank=True, db_column='draftDefId', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='draftdefid', to='dashboard.formdefs'),
        ),
        migrations.AddField(
            model_name='forms',
            name='projectid',
            field=models.ForeignKey(blank=True, db_column='projectId', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dashboard.projects'),
        ),
        migrations.AddField(
            model_name='publiclinks',
            name='createdby',
            field=models.ForeignKey(blank=True, db_column='createdBy', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='createdby', to='dashboard.actors'),
        ),
        migrations.AddField(
            model_name='publiclinks',
            name='formid',
            field=models.ForeignKey(blank=True, db_column='formId', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dashboard.forms'),
        ),
        migrations.AlterField(
            model_name='actees',
            name='id',
            field=models.CharField(max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='fieldkeys',
            name='actorid',
            field=models.OneToOneField(blank=True, db_column='actorId', null=True, on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, related_name='actor_id', serialize=False, to='dashboard.actors'),
        ),
        migrations.AlterField(
            model_name='publiclinks',
            name='actorid',
            field=models.OneToOneField(db_column='actorId', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, related_name='actorid', serialize=False, to='dashboard.actors'),
        ),
        migrations.AlterUniqueTogether(
            name='forms',
            unique_together={('projectid', 'xmlformid')},
        ),
    ]
