# Generated by Django 3.2 on 2022-08-22 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20220815_1459'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('actorid', models.OneToOneField(db_column='actorId', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='dashboard.actors')),
                ('password', models.CharField(blank=True, max_length=64, null=True)),
                ('mfasecret', models.CharField(blank=True, db_column='mfaSecret', max_length=20, null=True)),
                ('email', models.TextField()),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='actees',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='fieldkeys',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='forms',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='publiclinks',
            options={'managed': False},
        ),
    ]
